"""initial migrate

Revision ID: cb09cbe62f0c
Revises: 
Create Date: 2021-06-08 07:11:47.013091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb09cbe62f0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.String(length=100), nullable=True),
    sa.Column('data_size', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('extractor_id', sa.Integer(), nullable=True),
    sa.Column('data_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('_admin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('case')
    # ### end Alembic commands ###
