export const FETCH_MEMBERS = 'FETCH_MEMBERS'
export const FETCH_MEMBERS_FAILED = 'FETCH_MEMBERS_FAILED'
export const FETCH_MEMBERS_SUCCESSFULL = 'FETCH_MEMBERS_SUCCESSFULL'
export const SELECT_USER = 'SELECT_USER'