/*
    Types for Case Reducer.
*/

export const LOAD_CASE_TREE = 'LOAD_CASE_TREE';
export const LOAD_CASE_TREE_FAILED = 'LOAD_CASE_TREE_FAILED';
export const LOAD_CASE_TREE_SUCCESSFULL = 'LOAD_CASE_TREE_SUCCESSFULL';
export const LOAD_CASES = 'LOAD_CASES';
export const LOAD_CASES_FAILED = 'LOAD_CASES_FAILED';
export const LOAD_CASES_SUCCESSFULL = 'LOAD_CASES_SUCCESSFULL';

