/*
* Types definition of extract reducer.
*/

export const SET_DEFAULT_EXTRACT_DATA = 'SET_DEFAULT_EXTRACT_DATA'
export const EXTRACT_DATA = 'EXTRACT_DATA';
export const EXTRACT_DATE_FAILED = 'EXTRACT_DATA_FAILED';
export const EXTRACT_DATA_SUCCESSFULL = 'EXTRACT_DATA_SUCCESSFULL';