// Type definition for extractor related state

export const EXTRACTOR_DEFAULT = 'EXTRACTOR_DEFAULT';
export const FETCH_EXTRACTED_CASES = 'FETCH_EXTRACTED_CASES';
export const FETCH_EXTRACTED_CASES_FAILED = 'FETCH_EXTRACTED_CASES_FAILED';
export const FETCH_EXTRACTED_CASES_SUCCESSFULL = 'FETCH_EXTRACTED_CASES_SUCCESSFULL';