/*
* All Action types for management reducer.
*/

export const LOAD_COMPLETED_TASKS = 'LOAD_COMPLETED_TASKS'
export const LOAD_COMPLETED_TASKS_FAILED = 'LOAD_COMPLETED_TASKS_FAILED'
export const LOAD_COMPLETED_TASKS_SUCCESSFULL = 'LOAD_COMPLETED_TASKS_SUCCESSFULL'
export const LOAD_TODO_TASKS = 'LOAD_TODO_TASKS'
export const LOAD_TODO_TASKS_FAILED = 'LOAD_TODO_TASKS_FAILED'
export const LOAD_TODO_TASKS_SUCCESSFULL = 'LOAD_TODO_TASKS_SUCCESSFULL'
