/*
* All Action types for management reducer.
*/

export const LOAD_COMPLETED_TASKS = 'LOAD_COMPLETED_TASKS'
export const LOAD_COMPLETED_TASKS_FAILED = 'LOAD_COMPLETED_TASKS_FAILED'
export const LOAD_COMPLETED_TASKS_SUCCESSFULL = 'LOAD_COMPLETED_TASKS_SUCCESSFULL'
export const LOAD_TODO_TASKS = 'LOAD_TODO_TASKS'
export const LOAD_TODO_TASKS_FAILED = 'LOAD_TODO_TASKS_FAILED'
export const LOAD_TODO_TASKS_SUCCESSFULL = 'LOAD_TODO_TASKS_SUCCESSFULL'
export const LOAD_REPORT_GENERAL_INFO = 'LOAD_REPORT_GENERAL_INFO'
export const LOAD_REPORT_GENERAL_INFO_FAILED = 'LOAD_REPORT_GENERAL_INFO_FAILED'
export const LOAD_REPORT_GENERAL_INFO_SUCCESSFUL = 'LOAD_REPORT_GENERAL_INFO_SUCCESSFUL'
export const LOAD_REPORT_BROWSER_DATA = 'LOAD_REPORT_BROWSER_DATA'
export const LOAD_REPORT_BROWSER_DATA_FAILED = 'LOAD_REPORT_BROWSER_DATA_FAILED'
export const LOAD_REPORT_BROWSER_DATA_SUCCESSFUL = 'LOAD_REPORT_BROWSER_DATA_SUCCESSFUL'