/*
* All Action types for management reducer.
*/

export const LOAD_COMPLETED_TASKS = 'LOAD_COMPLETED_TASKS'
export const LOAD_COMPLETED_TASKS_FAILED = 'LOAD_COMPLETED_TASKS_FAILED'
export const LOAD_COMPLETED_TASKS_SUCCESSFULL = 'LOAD_COMPLETED_TASKS_SUCCESSFULL'
export const LOAD_TODO_TASKS = 'LOAD_TODO_TASKS'
export const LOAD_TODO_TASKS_FAILED = 'LOAD_TODO_TASKS_FAILED'
export const LOAD_TODO_TASKS_SUCCESSFULL = 'LOAD_TODO_TASKS_SUCCESSFULL'
export const LOAD_ANALYTICS_COMMON_WORD = 'LOAD_ANALYTICS_COMMON_WORD'
export const LOAD_ANALYTICS_COMMON_WORD_FAILED = 'LOAD_ANALYTICS_COMMON_WORD_FAILED'
export const LOAD_ANALYTICS_COMMON_WORD_SUCCESSFUL = 'LOAD_ANALYTICS_COMMON_WORD_SUCCESSFUL'
export const LOAD_ANALYTICS_MAXIMUM_COMMON_WORD = 'LOAD_ANALYTICS_MAXIMUM_COMMON_WORD'
export const LOAD_ANALYTICS_MAXIMUM_COMMON_WORD_FAILED = 'LOAD_ANALYTICS_MAXIMUM_COMMON_WORD_FAILED'
export const LOAD_ANALYTICS_MAXIMUM_COMMON_WORD_SUCCESSFUL = 'LOAD_ANALYTICS_MAXIMUM_COMMON_WORD_SUCCESSFUL'
